from django.conf.urls import patterns, url
from student import views
urlpatterns = patterns('', 
	url(r'^personality/$', views.personality, name="personality"),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^cal/$', views.calendar, name="cal"),
	url(r'^calevent/$', views.calEvent, name="events"),
	url(r'^planlist/$', views.planList, name="planlists"),
	url(r'^profile/$', views.studentProfile, name="studentprofile"),
	url(r'^qbank/ds/$', views.questionBankds, name="questionbank"),
	url(r'^qbank/ps/$', views.questionBankps, name="questionbank"),
	url(r'^qbank/rc/$', views.questionBankrc, name="questionbank"),
	url(r'^qbank/cr/$', views.questionBankcr, name="questionbank"),
	url(r'^qbank/sc/$', views.questionBanksc, name="questionbank"),
	url(r'^test/$', views.cat, name="cat"),
	url(r'^stocks/$', views.stock, name="highstock"),
	url(r'^stocks2/$', views.stock2, name="highstock"),
	url(r'^gd/$', views.genieDialogue, name="dialects"),
	url(r'^sd/$', views.studentDialogue, name="dialects"),
	url(r'^tutors/$', views.tutors, name="tutors"),
	url(r'^dashboard/tutor/(?P<username>\w+)$', views.tutorProfile, name="tutorprofiles"),
	url(r'^mailsent/$', views.mailSent, name="mails"),
	url(r'^logged-out/$', views.signout, name="signout"),
	)